import { useEffect, useMemo, useState } from "react"
import { motion } from "framer-motion"
import { AlertTriangle, ArrowRight, Clock3, RefreshCw, Search, TrainFront, X } from "lucide-react"
import { EurostarDisplayMenu, eurostarDisplayClass, useEurostarDisplay } from "./EurostarDisplay"
import { readResponseState, responseSourceMeta, staleLabel, type ResponseState } from "../lib/responseState"
import { DisabledServiceBanner, ServicePowerBadge } from "./ServicePowerBadge"

interface Hub {name:string;crs:string;services:number;delayed:number;cancelled:number;state:string}
interface Service {hub:string;scheduled:string;expected:string;delay:number;operator:string;destination:string;platform:string;status:string;trainId:string}
interface Alert {hub:string;message:string}
interface Data {hubs:Hub[];services:Service[];alerts:Alert[];fetchedAt:string;responseState?:ResponseState}

export function NationalRailCommandCenter({onClose,onAsk}:{readonly onClose:()=>void;readonly onAsk:(q:string)=>void}) {
  const [data,setData]=useState<Data|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [station,setStation]=useState("")
  const {theme,compact}=useEurostarDisplay()
  const sourceMeta=responseSourceMeta(data?.responseState)
  const serviceEnabled=!data?.responseState?.disabled
  const load=()=>{setLoading(true);fetch("http://localhost:8080/api/national-rail/command-center").then(async r=>{const body=await r.json().catch(()=>({})); const responseState=readResponseState(r, body); if(!r.ok){ if(responseState.disabled) return {hubs:[],services:[],alerts:[],fetchedAt:new Date().toISOString(),responseState} as Data; return Promise.reject(new Error((body as {error?:string}).error||"Feed unavailable")) } return {...body,responseState} as Data}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
  useEffect(load,[])
  const stats=useMemo(()=>{const hubs=data?.hubs||[];return{services:hubs.reduce((n,h)=>n+h.services,0),delayed:hubs.reduce((n,h)=>n+h.delayed,0),cancelled:hubs.reduce((n,h)=>n+h.cancelled,0)}},[data])
  const ask=(kind:"departures"|"arrivals")=>{if(!station.trim())return;onAsk(`Show live National Rail ${kind} ${kind==="departures"?"from":"at"} ${station.trim()}`);onClose()}
  return <motion.div className={`${eurostarDisplayClass(theme,compact)} fixed inset-0 z-[110] overflow-y-auto bg-[var(--es-bg)] text-[var(--es-text)]`} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>
    <header className="sticky top-0 z-20 border-b bg-[color-mix(in_srgb,var(--es-bg)_88%,transparent)] px-5 py-3 backdrop-blur-xl" style={{borderColor:"var(--es-border)"}}><div className="mx-auto flex max-w-7xl items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-[#17365d] text-white"><TrainFront size={18}/></span><div><div className="flex items-center gap-2"><h1 className="text-sm font-black">National Rail Command Center</h1><ServicePowerBadge enabled={serviceEnabled} label={serviceEnabled?"National Rail on":"National Rail off"} compact /></div><p className="text-[10px]" style={{color:"var(--es-muted)"}}>Live UK mainline terminal operations</p></div>{data?.responseState&&<div className="hidden items-center gap-2 rounded-full border px-2.5 py-1 text-[10px] font-black md:flex" style={{background:sourceMeta.bg,borderColor:sourceMeta.border,color:sourceMeta.text}}><span className="h-2 w-2 rounded-full" style={{background:sourceMeta.dot}}/>{sourceMeta.label}</div>}<div className="ml-auto flex gap-2"><EurostarDisplayMenu/><button onClick={load} className="flex h-8 w-8 items-center justify-center rounded-md border" style={{borderColor:"var(--es-border)"}} title="Refresh"><RefreshCw size={14} className={loading?"animate-spin":""}/></button><button onClick={onClose} className="flex h-8 w-8 items-center justify-center rounded-md border" style={{borderColor:"var(--es-border)"}} title="Close"><X size={15}/></button></div></div></header>
    <main className="mx-auto max-w-7xl px-5 py-6">
      {data?.responseState?.disabled&&<DisabledServiceBanner message={data.responseState.error||"National Rail has been disabled in Config > Services."} />}
      {data?.responseState?.stale&&<div className="mb-5 rounded-lg border border-amber-300 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-900">{staleLabel(data.responseState)} is being shown while National Rail live tools are unavailable.</div>}
      <section className="relative overflow-hidden bg-[#17365d] px-6 py-6 text-white sm:px-8"><div className="absolute inset-x-0 bottom-0 h-1 bg-[#ee7203]"/><div className="relative flex flex-wrap items-end gap-8"><div className="max-w-xl"><p className="text-[10px] font-black uppercase tracking-[.18em] text-white/55">Great British rail network</p><h2 className="mt-2 text-3xl font-black">Mainline movement, at a glance</h2><p className="mt-2 text-sm text-white/65">Live departures, platform intelligence and station notices across London’s principal terminals.</p></div><div className="ml-auto grid grid-cols-3 gap-6"><HeroMetric value={stats.services} label="Services"/><HeroMetric value={stats.delayed} label="Delayed" warn/><HeroMetric value={stats.cancelled} label="Cancelled" warn/></div></div></section>
      <section className="mt-5 grid gap-4 lg:grid-cols-[1.5fr_.8fr]">
        <div><div className="mb-3 flex items-center justify-between"><h3 className="text-xs font-black uppercase tracking-[.12em]">Terminal pulse</h3><span className="text-[10px]" style={{color:"var(--es-muted)"}}>{data?.fetchedAt?new Date(data.fetchedAt).toLocaleTimeString("en-GB"):"Waiting for feed"}</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data?.hubs.map((h,i)=><motion.div key={h.crs} className="es-themed-panel es-density-card border p-4" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.05}}><div className="flex items-center"><span className="font-mono text-xl font-black">{h.crs}</span><span className={`ml-auto h-2 w-2 rounded-full ${h.state==="live"?h.delayed||h.cancelled?"bg-amber-500":"bg-emerald-500":"bg-red-500"}`}/></div><p className="mt-1 truncate text-xs font-bold" style={{color:"var(--es-muted)"}}>{h.name}</p><div className="mt-4 flex gap-4 text-xs"><b>{h.services} trains</b><span className="text-amber-600">{h.delayed} late</span><span className="text-red-600">{h.cancelled} cancelled</span></div><div className="mt-3 h-1 overflow-hidden bg-[var(--es-surface-2)]"><motion.div className="h-full bg-[#ee7203]" initial={{width:0}} animate={{width:`${Math.max(8,100-(h.delayed+h.cancelled)*12)}%`}}/></div></motion.div>)}</div></div>
        <aside className="space-y-4"><div className="es-themed-panel border p-4"><h3 className="flex items-center gap-2 text-xs font-black"><Search size={14}/>Station board</h3><input value={station} onChange={e=>setStation(e.target.value)} placeholder="Station or CRS code" className="mt-3 w-full rounded-md border bg-transparent px-3 py-2.5 text-sm outline-none" style={{borderColor:"var(--es-border)"}}/><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>ask("departures")} className="flex items-center justify-center gap-2 rounded-md bg-[#17365d] px-3 py-2 text-xs font-black text-white">Departures <ArrowRight size={13}/></button><button onClick={()=>ask("arrivals")} className="rounded-md border px-3 py-2 text-xs font-black" style={{borderColor:"var(--es-border)"}}>Arrivals</button></div></div>{data?.alerts.slice(0,4).map((a,i)=><div key={i} className="es-themed-panel flex gap-3 border-l-4 border-l-amber-500 p-3 text-xs"><AlertTriangle size={15} className="shrink-0 text-amber-600"/><div><b>{a.hub}</b><p className="mt-1" style={{color:"var(--es-muted)"}}>{a.message}</p></div></div>)}</aside>
      </section>
      <section className="mt-6"><h3 className="mb-3 text-xs font-black uppercase tracking-[.12em]">Next movements</h3><div className="grid gap-2 md:grid-cols-2">{data?.services.slice(0,12).map((s,i)=><motion.div key={`${s.hub}-${s.trainId}-${i}`} className="es-themed-panel es-density-card grid grid-cols-[52px_44px_1fr_70px] items-center gap-3 border p-3" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.025}}><span className="font-mono text-base font-black">{s.scheduled}</span><span className="font-mono text-[10px] font-black" style={{color:"var(--es-muted)"}}>{s.hub}</span><div className="min-w-0"><b className="block truncate text-xs">{s.destination}</b><span className="block truncate text-[9px]" style={{color:"var(--es-muted)"}}>{s.operator}</span></div><div className="text-right"><b className={s.delay?"text-amber-600":"text-emerald-600"}>{s.delay?`+${s.delay}`:"On time"}</b><span className="block text-[9px]">Plat. {s.platform}</span></div></motion.div>)}</div></section>
      {error&&<div className="mt-5 border border-red-400 bg-red-50 p-4 text-sm text-red-800">{error}</div>}{loading&&!data&&<div className="flex items-center justify-center gap-2 py-20"><Clock3 size={17} className="animate-pulse"/>Loading live National Rail operations…</div>}
    </main>
  </motion.div>
}
function HeroMetric({value,label,warn=false}:{value:number;label:string;warn?:boolean}){return <div><div className={`text-2xl font-black ${warn&&value?"text-amber-300":""}`}>{value}</div><div className="text-[9px] font-bold uppercase text-white/45">{label}</div></div>}
